pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolution {
    eachPlugin {
        if (requested.id.id == 'com.android.application') {
            useModule('com.android.tools.build:gradle:8.1.0')
        }
    }
}
rootProject.name = "Daily Life Manager Pro"
include(":app")